### PR TITLE
[pending on openssl/general-policies#31] Drop the old platform policy file, as it is now in general-policies

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by t-j-h — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]
Approved subject to openssl/general-policies#31 being merged.

**Comment by levitte** [comment]
> Approved subject to [openssl/general-policies#31](https://github.com/openssl/general-policies/pull/31) being merged.

Yes...  that's why I have the "[pending..." bit in the PR title :wink:

**Review by mattcaswell — CHANGES_REQUESTED** [review]
Doesn't policies/general/dirdata.yaml also need an update?

If you feel like it you could also remove travel.md since we have a new travel policy now.

**Comment by levitte** [comment]
> Doesn't policies/general/dirdata.yaml also need an update?

Very good point!

> If you feel like it you could also remove travel.md since we have a new travel policy now.

See #366

**Review by mattcaswell — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

2b8c7b112fc03cefe76266bb6c146842fd283d84 Drop the old platform policy file, as it is now in general-policies

**Pull request closed without merging**
