### PR TITLE
typo

### LINKED ISSUE #86: Typo in the faq page: "finder pointers"
https://www.openssl.org/docs/faq.html#toc

In the following sentence:
"You can finder pointers to binary distributions in https://www.openssl.org/community/binaries.html . "

s/finder/find

### PR DESCRIPTION
**Pull request by iamamoose**
fixes: #86

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mspncp** [comment]
Oh c'mon guys! How low do you want to set the bar for the quality of commit messages? Shouldn't we team members provide a good example for others to follow?

**Comment by iamamoose** [comment]
> Oh c'mon guys! How low do you want to set the bar for the quality of commit messages? Shouldn't we team members provide a good example for others to follow?

We are talking about a 2 character diff fix to the website (not the main code) which has been sitting waiting for someone to do it for nearly 2 years (probably because of the effort to create a PR and review for it).

**Comment by mspncp** [comment]
Compared to the effort you had to make the change, commit it, and create a pull request for it, the effort to add a little sentence like "Fix a typo in the faq page" is practically negligible. So I can't really follow your argument. But YMMV.

**Comment by mspncp** [comment]
Thanks for extending your commit message. And sorry if I sounded rude.

**Pull request merged**
