### PR TITLE
code health: engine branch

### PR DESCRIPTION
**Pull request by paulidale**
Move the engine branch question to old.

### CODE REVIEW

**Comment by t-j-h** [comment]
I would just delete it - the version to which it applies is long since EOLd.

**Comment by levitte** [comment]
I agree with @t-j-h

**Comment by paulidale** [comment]
Okay, removed now.

**Review by mattcaswell — APPROVED** [review]
Approved - but there is a conflict now.

**Comment by paulidale** [comment]
rebased and the conflict is gone.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
