### PR TITLE
bin/mk-manpages3: install more than just HTML files

### PR DESCRIPTION
**Pull request by levitte**
OpenSSL 3.0 now sports images as well.

### CODE REVIEW

**Comment by levitte** [comment]
I have this currently live on beta.openssl.org, see for example https://beta.openssl.org/docs/manmaster/man7/life_cycle-kdf.html

**Review by paulidale — APPROVED** [review]
Should I update the images to match the background colour of the pages?

**Comment by t8m** [comment]
> Should I update the images to match the background colour of the pages?

Could the background be made transparent? These are .png files...

**Comment by levitte** [comment]
> Should I update the images to match the background colour of the pages?

Make the background transparent, then you don't have to even ask.

**Comment by levitte** [comment]
Merged

2e8cfad0e7a3155e8cdeae1a2d9d0cfa9a4efe80 bin/mk-manpages3: install more than just HTML files

**Comment by paulidale** [comment]
Background are now transparent: openssl/openssl#15616

The node ellipses might not be ideal in the background colour but it's good enough for now.

**Comment by levitte** [comment]
> The node ellipses might not be ideal in the background colour but it's good enough for now.

can't the edge smoothing be made with transparency?

**Comment by paulidale** [comment]
I've no idea how or if that would be required.

I was thinking about distinguishing the ellipses from the background.  Probably not important.

**Pull request closed without merging**
