### PR TITLE
Fix the link to the OTC page

### PR DESCRIPTION
**Pull request by t8m**
Fixes a mistake from #321

### CODE REVIEW

**Comment by t8m** [comment]
Any idea why the Makefile update did not make the PGP fingerprints to be added to the OTC page?

**Comment by levitte** [comment]
> Any idea why the Makefile update did not make the PGP fingerprints to be added to the OTC page?

I looked just now.  The production of `community/otc.inc` doesn't depend on `Makefile`, so the option change goes unnoticed...

**Comment by levitte** [comment]
I'll have a look at the dependencies and will submit a PR that fixes it (BTW, see #320 and #326, the latter is somewhat related)

**Review by levitte — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
@openssl/omc, second approval needed

**Comment by levitte** [comment]
For dependencies, also see #330

**Comment by levitte** [comment]
Merged

ae9f54c364970430cbfe5d4c4351718e3fd9432f Fix the link to the OTC page

**Pull request closed without merging**
