### PR TITLE
Release strategy fixes

### PR DESCRIPTION
**Pull request by levitte**
- Added information on new versioning scheme
- Added or changed support dates
- Generalised information on alpha, beta, and release criteria
- Removed 1.1.1 timetable

### CODE REVIEW

**Comment by levitte** [comment]
Darn, I had forgotten about #82.  @mattcaswell, I'm happy to toss this unless it adds something significant (to be investigated later, I can hardly keep awake now...)

**Comment by levitte** [comment]
Looking at #82 again, it seems to me that this PR would work in combination with that.

**Comment by mspncp** [comment]
ping?

**Comment by mattcaswell** [comment]
I added these commits into #82.

**Comment by levitte** [comment]
Cool, I will close this

**Pull request closed without merging**
