### PR TITLE
Kill the FAQ

### PR DESCRIPTION
**Pull request by levitte**
It's unused and hasn't seen an update for eons.

### CODE REVIEW

**Comment by arapov** [comment]
Partly fixes openssl/project#122

**Review by mattcaswell — CHANGES_REQUESTED** [review]
I see numerous other FAQ leftovers not addressed by this PR:

.htaccess
inc/pandoc-body-prologue.html5
inc/banner.shtml
inc/screen.css
source/index.md
dirdata.yaml
docs/index.md
docs/dirdata.yaml

**Comment by levitte** [comment]
> I see numerous other FAQ leftovers not addressed by this PR:
> 
> .htaccess
> inc/pandoc-body-prologue.html5
> inc/banner.shtml
> inc/screen.css
> source/index.md
> dirdata.yaml
> docs/index.md
> docs/dirdata.yaml

~~Er...  what makes you think these files are just for the FAQ?~~
Oh, ah, edits to do.  Right

**Comment by levitte** [comment]
This needed a rebase after the move to tt includes.  Done

**Comment by levitte** [comment]
I think I got all the FAQ references now.

We should probably follow up with another PR that links to the github discussions.

**Review by mattcaswell — APPROVED** [review]

**Review by arapov — APPROVED** [review]

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
