### PR TITLE
Remove redundancy

### PR DESCRIPTION
**Pull request by levitte**
There's a lot of redundancy in our web generation, and the most glaring one is how we have release series copied all over the place.

This set of commits tries to resolve that issue by having all release versions specified in the Makefile and passing that down to the scripts.

This also automates the generation of release version specific files by using templates.  [Template Toolkit](http://www.template-toolkit.org/) become the template driver of choice.

### CODE REVIEW

**Comment by levitte** [comment]
https://beta.openssl.org/ is currently generated using this change.  Please have a look.

**Comment by richsalz** [comment]
This doesn't seem like an improvement in readability to me.  Eval and foreach to create rules...

**Comment by levitte** [comment]
How would you do it then?

**Comment by levitte** [comment]
What I'm trying to do with this is reduce the maintenance issue with having release versions repeated all over the place.  It's error prone, and this effort has already uncovered a few glaring mistakes:

-   https://www.openssl.org/news/changelog.html : 
    > For other branches, the changelogs are distributed with the source, but are also available here:
    > *    1.0.2
    > *    1.1.0

    *Oops, where did 1.1.1 go?*
-   https://www.openssl.org/docs/manmaster/man5/ : 
    > ## crypto library

    *Oops, wrong title, obvious copying error*
-   https://www.openssl.org/docs/manmaster/man7/ : 
    Same mistake as with man5.

Mistakes happen, and sure they can get corrected, but the annoying thing is that they happen again...  and again...

**Comment by mspncp** [comment]
IMO the foreach rules are more concise and improve maintainability. As for the eval's: yes, they are difficult to "reverse engineer" in one's head, it might help to add some explaining comments.

**Comment by richsalz** [comment]
One way to do it is to have a script generate the Makefile.
I don't recall seeing errors with new releases, but I haven't maintained the website in some time.

**Comment by levitte** [comment]
> One way to do it is to have a script generate the Makefile.

I was considering that, actually.  A sub-Makefile...  but I'm unsure how that would make it more readable.  Possibly the *main* Makefile would become more readable by not having all the cruft inside, sure, but that can as easily be arranged by reorganizing the current Makefile...  that's something I leav for another PR, though (I'm planning on quite a bit of cleanup...  just you wait 'til I start with the CSS stuff...  the octopress cruft is, well, cruft, obviously collected over years of development)

**Comment by richsalz** [comment]
Shrug.  I dislike this change, @mspncp seems okay with it.

**Comment by levitte** [comment]
I can make an extra effort and add some extra commenting.

**Comment by levitte** [comment]
I added a lot of commentary, I hope that helps

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
