### PR TITLE
Convert SSI includes to tt

### PR DESCRIPTION
**Pull request by levitte**
#325 specifies that all server side includes should be banned, and
replaced with [Template Toolkit](http://template-toolkit.org/)
includes instead.

For the most part, this change is fairly easy, with just a bit of logic
rearrangement.

This allows the resulting pages to be truly static and viewable
wherever they're are built, even as file: links such as
`file:///PATH/TO/openssl/web/index.html`.  It also means that they can
be pushed to any storage without care for special web server support,
and makes them cache friendly too.

### CODE REVIEW

**Comment by levitte** [comment]
This is currently in draft.  Manpage production is a bit more
challenging, and I'm focusing on that today.

**Comment by levitte** [comment]
I finally got it working right.  We've had a few small bugs in web
production for a while, that made some page details look a bit weird.
I fixed them too while I was at it.

**Comment by levitte** [comment]
I'm currently building this PR on https://beta.openssl.org/.  It takes
a moment with docs and all, so have a look in half an hour or tomorrow.

**Review by vavroch2010 — APPROVED** [review]

**Comment by levitte** [comment]
@openssl/omc (need an OMC approval)

**Review by arapov — APPROVED** [review]

**Comment by levitte** [comment]
Merged

3e7c5782e9db2a38766c5a6839d71cf1e21bc1d7 Add a Makefile rule to allow tpage templates for anything
d20569c8e342b908f07b8d05b58e72745494769f Add a markdown copy of inc/legalities.md
d0d42d82433bc44a0199ee6f7bcea0759dc16bec Convert SSI includes to tt includes in community/
55928bc688b11a50b519f527c8ccd77ba7f5e25f Convert SSI includes to tt includes in docs/
ec5b365caf743f85876812a8f04286cdd6af7e37 Convert SSI includes to tt includes in top directory
7b1bc58eeba962fad7ff05ddf3174254f43d6907 Convert SSI includes to tt includes in news/
3e0fca06da615998cf45b9eab7f8274fe886e029 Convert SSI includes to tt includes in policies/
25959f5958a3ed0abfd8d20f2395ce1874cfe7a8 Convert SSI includes to tt includes in source/
0ef7190d81f85ed781799e90a14b581693118dd0 Avoid rendering README.md
655ce394df2f80f9179f77206e8ec59dfbdfd065 Ignore temporary OpenSSL build and install directories
028c0c7b0c544c036cb7c1e7c6e9d1ec4b1033f8 Small fix in bin/mk-mancross: skip missing docs directories
58c8d7ce29f43e32fcd3396fe0cd0b64e6e987f5 Convert SSI includes to tt includes in manpages
d52e96656eb1fe91de4765289a7a3fbcb5cdd83c Fix support/dirdata.yaml to produce more correct breadcrumbs
9f137781b40d842ef7a72053b09d25b113672dae Remove the SSI artifacts, they are not needed any more

**Pull request closed without merging**
