### PR TITLE
Attempt to add a FAQ about TLS security levels

### PR DESCRIPTION
**Pull request by kaduk**
The title of the question might need some work, and one could argue that the response is too detailed.

### CODE REVIEW

**Comment by richsalz** [comment]
the website doesn't have the strict review policy, so if you can merge do so.  else i will

**Comment by mattcaswell** [comment]
Nevertheless, I still think its a good idea to request reviews for website changes. Maybe we should make it a formal requirement.

**Review by mattcaswell — COMMENTED** [review]
Approved

**Comment by t-j-h** [comment]
Extending the review policy to openssl-web is sensible.

**Comment by kaduk** [comment]
@richsalz As far as I can tell, I do not even have read permission to the authoritative web.git, let alone write.

**Comment by levitte** [comment]
@kaduk, that could be because the name of the authoritative repo is openssl-web.git...

**Comment by levitte** [comment]
(note that you still don't have write permissions for it...  openssl-web is OMC turf)

**Comment by levitte** [comment]
So @mattcaswell, wanna merge this?

**Comment by richsalz** [comment]
merging now.

**Pull request closed without merging**
