### PR TITLE
Fix advisory link

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by richsalz** [comment]
Can/should we somehow figure out a way to automate this, or at least list all the steps in our tooling?

**Comment by mattcaswell** [comment]
> Can/should we somehow figure out a way to automate this, or at least list all the steps in our tooling?

It's actually already heavily automated - but garbage in garbage out. Getting this xml right is the first step for the subsequent automated steps! I suppose we could attempt to take the automation back a step earlier to auto generate the xml from the advisory, but I'm not sure how easy that would be.

There is some level of documentation here:
https://github.com/openssl/tools/blob/master/release-tools/README.md

**Comment by richsalz** [comment]
I know about that file, I kinda re-wrote it. :)  Should we maybe add "xml lint" to the steps?  I'll think a bit.

**Comment by mattcaswell** [comment]
> I know about that file, I kinda re-wrote it. :) Should we maybe add "xml lint" to the steps? I'll think a bit.

We already validate the xml when we process it to auto-generate the CVE updates for MITRE (although I guess that happens relatively late in the process). It could be brought forward. Although that wouldn't have caught this issue.

**Comment by richsalz** [comment]
yeah, maybe checking for the top date being within two weeks of today?  not sure that's worth it.

**Pull request closed without merging**
