### PR TITLE
Add newsflash about the release of OpenSSL 3.0 alpha11

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by t8m — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
Merged

15c3d9188ef04d9d3d4b98088d641163390a5e03 Add newsflash about the release of OpenSSL 3.0 alpha11

**Comment by mattcaswell** [comment]
Retrospectively approved.

Strictly speaking the web repo requires an OMC approval (we should perhaps fix that).

**Comment by levitte** [comment]
> Strictly speaking the web repo requires an OMC approval (we should perhaps fix that).

I'm confusing things, it seems...  I thought the only thing was that it requires an OMC member to actually push to our main repo, but never remember that this extends to approvals as well...  this being a purely technical update, I don't see why an OTC member couldn't approve.

**Comment by mattcaswell** [comment]
> I thought the only thing was that it requires an OMC member to actually push to our main repo, but never remember that this extends to approvals as well

No, an OMC approval is needed.

> I don't see why an OTC member couldn't approve.

That may not be a bad idea, but it is not our current rules.

**Comment by t8m** [comment]
Doesn't the rule of implicit approval by the person who created the PR count? I.E. if OMC member submits a web PR, it should be sufficient to get committer approval. And if that is not sufficient, perhaps the rule should change to make it so? So it is similar to the main repo rule except here the one (possibly implicit) approval would have to be OMC.

**Comment by mattcaswell** [comment]
> Doesn't the rule of implicit approval by the person who created the PR count?

Yes, but that doesn't help. *Both* approvals must be OMC. Committer or OTC approvals don't count in the web repo at all. I'm not saying any of this is *right* - just that that is the way the rules *are*.

**Comment by t8m** [comment]
OK, that makes sense. Perhaps OMC could think about changing this to require only one OMC and one committer approval.

**Pull request closed without merging**
