### PR TITLE
Add policy on assertion usage

### LINKED ISSUE #2264: document our assert policy
From a comment by @mattcaswell in #2259:
```
I thought the consensus was heading towards using soft asserts followed by an "if" for the same condition. That should mean that a debug build that fails the assert will abort, but a non debug build will just return from the function with an error. That at least was the approach we took in the original WPACKET implementation (as you can see elsewhere in the file).
```

That's sensible and good, we should vote and make it an explicit part of our style doc.  There's bound to be some discussion.

### PR DESCRIPTION
**Pull request by nickthetait**
Fixes https://github.com/openssl/openssl/issues/2264

### CODE REVIEW

**Comment by richsalz** [comment]
We'll discuss this on the openssl-project mailing list (https://mta.openssl.org for details) and then the OMC will vote.  Thanks!

**Comment by richsalz** [comment]
This was addressed by #43; the vote did not pass so I am closing this, I guess as WONTFIX.

**Comment by levitte** [comment]
> This was addressed by #43; the vote did not pass so I am closing this, I guess as WONTFIX.

You can't assume WONTFIX for this.  The vote did not pass because of *other* passages of the #43 proposal.

**Comment by richsalz** [comment]
I am not commenting on non-public reasons that some OMC members might have given. The point is we had a discussion and vote, that included this, and it did not pass.  If you are going to bring the issue back up, then you can re-open this issue.

**Comment by levitte** [comment]
@openssl/otc, if this is of interest, someone should pick it up and rework it for openssl/technical-policies

**Comment by t8m** [comment]
Replaced with  openssl/technical-policies#49 issue. Someone would still need to do a PR for it though.

**Pull request closed without merging**
