### PR TITLE
Consolidate some FIPS pages into one

### PR DESCRIPTION
**Pull request by richsalz**
Remove unused image/logo files.

ping @t-j-h

### CODE REVIEW

**Comment by levitte** [comment]
Not sure I understand why we should remove the sponsor links...  Mind sharing your thoughts on that one?

**Comment by richsalz** [comment]
Because it's not an infinite-time credit.  It's been more than five years.  And it's a mostly-shut-down project now.

**Review by t-j-h — COMMENTED** [review]
I think this change makes sense - other views?
Leaving it open for other comments.

**Comment by richsalz** [comment]
There was a question/comment from @levitte about removing old sponsor logo's. I'm not sure if he's satisfied with the answer or not. But we don't have a policy about requiring reviews (despite my nudging a couple of times; I'm not going to run that vote), so I'm going to push this in a couple of hours unless Richard's very upset.  But I guess, if he is, he can always revert the commit :)

**Comment by levitte** [comment]
I'm fine with your explanation. Sorry for the late response

**Comment by richsalz** [comment]
Thanks!

**Pull request merged**
