### PR TITLE
bin/mk-latest: Adapt .htaccess for the version scheme of OpenSSL 3.0

### LINKED ISSUE #229: Please don't delete old alpha tarballs
Hi,

ten days ago I added OpenSSL 3.0.0-alpha14 to CPython's pre-commit CI. Our CI just broke because 
https://www.openssl.org/source/openssl-3.0.0-alpha14.tar.gz has been deleted and GH purged our build caches. I haven't had time to update Python 3.8 and 3.9 feature branches.

Please keep older alphas around for a little while longer.

Thanks!

### PR DESCRIPTION
**Pull request by levitte**
Fixes #229

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
You beat me to it! I just figured out the same fix.

Can we also fix the fact the 3.0 doesn't appear in https://www.openssl.org/source/old/

**Comment by levitte** [comment]
> Can we also fix the fact the 3.0 doesn't appear in https://www.openssl.org/source/old/

Raise an issue for it please, it's a bit more involved.

**Comment by mattcaswell** [comment]
> Raise an issue for it please, it's a bit more involved.

Raised as #231

**Comment by levitte** [comment]
Merged

650e079c69473944f2731e6a964d260a2a6dff61 bin/mk-latest: Adapt .htaccess for the version scheme of OpenSSL 3.0

**Comment by levitte** [comment]
Darn, this wasn't good enough...

**Pull request closed without merging**
