### PR TITLE
Better dependencies for md->html rendering

### PR DESCRIPTION
**Pull request by levitte**
It's too easy to miss adding proper dependencies, so let's make that
automatic, at least for md files we have in this repository.

All md->html rendering is made to depend on the presence of dirdata.yaml,
which will be a good reminder to add it where it's missing.

### CODE REVIEW

**Comment by levitte** [comment]
This depends on #320.  Without that one, building from this PR will fail because of the missing top level `dirdata.yaml`

**Comment by levitte** [comment]
With #320 approved and merged, this is now rebased and ready for review

**Comment by levitte** [comment]
Note that [www.openssl.org/roadmap.html](https://www.openssl.org/roadmap.html) currently lacks the expected breadcrumbs, in spite of #320.  That's because the dependencies for `roadmap.html` in Makefile doesn't specify `dirdata.yaml`.  This PR resolves that.

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged

0de56ea2c9ec83432cb562305fa81c5fe1d1828b Better dependencies for md->html rendering

**Pull request closed without merging**
