### PR TITLE
Make an 'apropos' like table from the manpages, rather than a filelist

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by richsalz** [comment]
Nice work.  Looking at https://beta.openssl.org/docs/manmaster/man3/ (and for man1.1.1), there is a wrong line there:
```
 <header><h2>crypto library</h2></header>
```

**Comment by levitte** [comment]
Merged

c49be85acdf6d10bfb17d0a5f1cb6405ae25fcaf Generate apropos-like tables instead of filelists for manpages
064a3b32b4890eff85cb8c905d91cf361673e485 Have bin/mk-manpages and bin/mk-newmanpages add a description comment
6869d8b6065b187af840f29a574dace73d05f3c4 Change getnames() to getdata(), for generic data retrieval from POD files

**Comment by mspncp** [comment]
Cool, nice work! And really quick. But didn't you say you were going back to vacation mode? ;-)

**Comment by levitte** [comment]
(hush :wink:)

**Comment by levitte** [comment]
I've been playing with JS and CSS this week, and well, it made me think of OpenSSL's web.  As good a playing field as any...

**Pull request closed without merging**
