### PR TITLE
Keep publishing manuals for 1.0.2

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

84eb4f90c1b8f0b0d3024151edcd32f829fbd5cb Keep publishing manuals for 1.0.2

**Comment by mattcaswell** [comment]
Hmmm....this doesn't seem quite right yet. I can access the man pages if I go to them directly:

https://www.openssl.org/docs/man1.0.2/

But they are not listed here:

https://www.openssl.org/docs/manpages.html

Nor are they listed as an alternative on the manpages bar on the right hand side of the page here or on other pages (only master, 3.0 and 1.1.1 are listed):

https://www.openssl.org/docs/man1.1.1/

**Comment by levitte** [comment]
> Hmmm....this doesn't seem quite right yet. I can access the man pages if I go to them directly:
> 
> https://www.openssl.org/docs/man1.0.2/
> 
> But they are not listed here:
> 
> https://www.openssl.org/docs/manpages.html
> 
> Nor are they listed as an alternative on the manpages bar on the right hand side of the page here or on other pages (only master, 3.0 and 1.1.1 are listed):
> 
> https://www.openssl.org/docs/man1.1.1/

I'll submit an update PR

**Comment by levitte** [comment]
See #296

**Pull request closed without merging**
