### PR TITLE
Fix typo in Policies intro

### PR DESCRIPTION
**Pull request by jamuir**
I wanted to fix this:

> This includes how spend some money, as detailed in the [travel reimbursement policy](https://www.openssl.org/policies/general/travel-policy.html).

I changed it to "how we spend some money", but there may be a better rewording.

### CODE REVIEW

**Comment by jamuir** [comment]
@arapov @levitte : please take a look.

**Review by t8m — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Second @openssl/omc approval needed

**Review by paulidale — APPROVED** [review]

**Comment by jamuir** [comment]
This has been merged, but the typo it fixes is still present on openssl.org.

**Comment by paulidale** [comment]
Incorrectly merged.  This needs to be merged on our repository not the public one.
Which I've now done.

**Comment by jamuir** [comment]
Thanks, Pauli.

**Pull request merged**
