### PR TITLE
Fix typo in *are encouraged* on *Downloads* page

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by paulmenzel** [comment]
Thanks.

Out of curiosity, why not just merge it using GitHubs button, so it’s marked as *merged* in GitHubs interface? Closing the merge/pull request makes it indistinguishable from “rejected” (closed) merge/pull requests.

**Comment by t8m** [comment]
You can distinguish the merged PRs by the 
`openssl-machine pushed a commit that referenced this pull request`
message above.

The primary git repository is not on GitHub so that's the reason why the GitHub merge button would not work.

**Comment by t8m** [comment]
Also the commits are annotated with Reviewed-by and possibly other things before merging.

**Comment by mspncp** [comment]
@paulmenzel to satisfy your curiousity a little bit more: as @t8m already told you, we amend the commit messages locally with review comments before we rebase onto master and push the result to git.openssl.org. From there the commits are mirrored to GitHub. That's why the GitHub 'merge' button is not usable for us. But an interesting related question is: how does GitHub determine whether a PR was merged or not, in particular in repositories like ours which have linear history enforced, whence there is no merge commit as indicator for the merge?

The answer (based solely on my observations) is: GitHub does not store any meta data indicating "PR was merged". Instead, the criterion is simply whether the head of the PR branch is contained in the 'master' branch or not. While the GitHub merge button rebases and adjusts the owner branch automatically, our scripts don't do that. Some committers however (in particular @DDvO) use a script which adjusts their own branch as well, and consequently GitHub displays their pull requests as merged.

For example, pull request https://github.com/openssl/openssl/pull/13906 by @DDvO has a violet "merged" indicator. This is because the HEAD of [DDvO:add_SSL_ERROR_WANT_RETRY_VERIFY](https://github.com/DDvO/openssl/commits/add_SSL_ERROR_WANT_RETRY_VERIFY), (which coincides with the reference `refs/pull/13906/head`) in [openssl/openssl](https://github.com/openssl/openssl)  is at [0c3eb27](https://github.com/openssl/openssl/commits/0c3eb2793b2a1fe35beeb90ba8f5cb2a0fdc3270), which is contained in the master branch.


```
$ git ls-remote https://github.com/openssl/openssl.git | grep 13906
0c3eb2793b2a1fe35beeb90ba8f5cb2a0fdc3270        refs/pull/13906/head

$ git branch --contains 0c3eb2793b2a1fe35beeb90ba8f5cb2a0fdc3270 | grep master
* master
```

_(@DDvO: did you stop using that script, or did you change it? Your recent PRs aren't marked as "merged" anymore.)_

**Comment by paulmenzel** [comment]
> You can distinguish the merged PRs by the `openssl-machine pushed a commit that referenced this pull request` message above.

Yes, but that’s not visible in the [overview](https://github.com/openssl/web/pulls?page=1&q=is%3Apr+is%3Aclosed).

**Comment by paulmenzel** [comment]
> Also the commits are annotated with Reviewed-by and possibly other things before merging.

By default, GitHub allows you to edit the branch. You could force-push your version to the GitHub branch then.

**Comment by paulmenzel** [comment]
> @paulmenzel to satisfy your curiousity a little bit more:

Thank you for the detailed reply.

> as @t8m already told you, we amend the commit messages locally with review comments before we rebase onto master and push the result to git.openssl.org. From there the commits are mirrored to GitHub. That's why the GitHub 'merge' button is not usable for us.

You could force push your amended commit to GitHub. Then GitHub could make the connection.

> But an interesting related question is: how does GitHub determine whether a PR was merged or not, in particular in repositories like ours which have linear history enforced, whence there is no merge commit as indicator for the merge?
> 
> The answer (based solely on my observations) is: GitHub does not store any meta data indicating "PR was merged". Instead, the criterion is simply whether the head of the PR branch is contained in the 'master' branch or not.

Yes, the commit hash has to be in the master branch to make the connection.

> While the GitHub merge button rebases and adjusts the owner branch automatically, our scripts don't do that.

Personally, I prefer merges, and wouldn’t use GitHub’s rebase feature.

[…]

Thank you again for all your answers.

**Comment by DDvO** [comment]
> (@DDvO: did you stop using that script, or did you change it? Your recent PRs aren't marked as "merged" anymore.)

@mspncp, I usually use `ghmerge`, which does not modify the PR branch.
This is for simplicity and due to the concern that when modifying the PR branch 
then it is strictly speaking no more exactly the one that has been approved.

Sometimes I anyway decided it would be nice to get the purple 'Merged' icon.
In this case my procedure its to rebase the PR branch on master, use `addrev` on it, 
and then use `ghmerge` (with the same `prnum` and reviewer data as arguments).

**Comment by mattcaswell** [comment]
> due to the concern that when modifying the PR branch
then it is strictly speaking no more exactly the one that has been approved.

This is why I don't like pushing back to GH to get the merged icon. I prefer to keep the PR in the state that it was approved in.

**Comment by mspncp** [comment]
@paulmenzel I agree with @mattcaswell's point of view: Formally, any force-push to the PR branch after a review invalidates the existing approvals. In fact, a GitHub repository can be configured to invalidate existing approvals automatically in case of a push to the PR branch.

Although the GitHub 'merge' button force-pushes a rebased version of the PR branch (if you have configured linear history, i.e., no merge commits), this case is somewhat different, because the rebase-and-force-push is done by a 'trusted authority'.  Since we don't rely on the 'merge' button, it's better to leave the PR branch untouched. Having the approved state archived outweighs the benefits of seeing violet merge icons ;-).

**Comment by DDvO** [comment]
> > due to the concern that when modifying the PR branch
> > then it is strictly speaking no more exactly the one that has been approved.
> 
> This is why I don't like pushing back to GH to get the merged icon.
> I prefer to keep the PR in the state that it was approved in.

I agree.
A pity that GitHub does not provide better support for this approach.
BTW, I had discovered the current way of getting the purple icon by mistake (I think it was for PR #10667).

**Comment by DDvO** [comment]
> Although the GitHub 'merge' button force-pushes a rebased version of the PR branch (if you have configured linear history, i.e., no merge commits), this case is somewhat different, because the rebase-and-force-push is done by a 'trusted authority'. Since we don't rely on the 'merge' button

Can you remind me what the reason is why we don't use the merge button?
What you wrote here almost sounds as if it does what we would like to have, 
but there must be some drawback. Is it because it does a forced push rather than a normal one?

**Comment by mspncp** [comment]
The simple reason why we don't use the 'merge' button is because the GitHub repository is just a public mirror of our central repository [git.openssl.org:openssl.git](https://git.openssl.org/?p=openssl.git;a=summary) . So unless we decide to make the GitHub repository our central one and change our entire workflow, using the 'merge' button won't be possible.

**Comment by t8m** [comment]
We could ask GitHub for "Close and mark as merged" button :grin:

**Comment by t8m** [comment]
https://github.community/t/feature-request-mark-pull-request-as-merged/14194

**Pull request closed without merging**
