### PR TITLE
Add BSD-armv4 platform

### PR DESCRIPTION
**Pull request by pkubaj**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ping @openssl/omc for second review.

**Comment by t8m** [comment]
@levitte @paulidale @t-j-h

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I'm hitting CLA issues when I try to merge this.

**Comment by pkubaj** [comment]
I pushed a new commit with my FreeBSD.org address. Is that ok?

**Comment by paulidale** [comment]
Yes, thanks.  It should go live on the web site in a few minutes.

Which brings up a question: should a community maintainer necessarily have a CLA on file?

**Comment by t-j-h** [comment]
> Which brings up a question: should a community maintainer necessarily have a CLA on file?

Yes - that should be a requirement - as the whole point of being a maintainer is about being able to test and contribute any required adjustments. We really should have put that into the list if requirements and we should encourage those who haven't yet got a CLA on file to get them in place.

**Pull request closed without merging**
