### PR TITLE
Update policies/omc-bylaws.md with a history line re the minor edit clause

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by t-j-h** [comment]
You also need to hit the last modified up the top of the file - or remove it so we just run off the history at the bottom.
It is strange to have redundant information like that. So either edit both or remove one in your update.

**Comment by levitte** [comment]
> You also need to hit the last modified up the top of the file - or remove it so we just run off the history at the bottom. It is strange to have redundant information like that. So either edit both or remove one in your update.

Thanks.  I removed the top line.

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
agree minor-edit

**Review by paulidale — APPROVED** [review]
Yes, minor.

**Comment by levitte** [comment]
Merged

b2b17e519646cb29fe3a823b7e9ae875e071bd3c Update policies/omc-bylaws.md with a history line re the minor edit clause
0b6f40f52f7171d4096ab82cc7bc0802e396dc68 Remove the top date record

**Pull request closed without merging**
