### PR TITLE
Roadmap web update

### PR DESCRIPTION
**Pull request by mkoci-koca**

### CODE REVIEW

**Comment by mattcaswell** [comment]
Looks like there is a conflict that needs resolution already.....you will need to rebase.

Also you added a jpg but didn't seem to reference it from anywhere?

**Comment by hlandau** [comment]
The image is a bit odd for a public communication. If we want an image we probably want something more straightforward. Though I don't think we need an image.

**Comment by levitte** [comment]
I agree that the image is unnecessary.

It's also confusing:

1. What is "basecamp"? I believe that many won't know
2. 3.2 is called just QUIC, which is misleading, as it isn't going to be the complete protocol

**Comment by mkoci-koca** [comment]
> I agree that the image is unnecessary.
> 
> It's also confusing:
> 
> 1. What is "basecamp"? I believe that many won't know
> 2. 3.2 is called just QUIC, which is misleading, as it isn't going to be the complete protocol

Right, the image shouldn't have been part of the PR. Sorry, I will remove it.

**Comment by mkoci-koca** [comment]
> Looks like there is a conflict that needs resolution already.....you will need to rebase.
> 
> Also you added a jpg but didn't seem to reference it from anywhere?

I will remove the jpg it shouldn't have been part of the PR

**Comment by mattcaswell** [comment]
This PR also seems to include unrelated changes to contracts.html which are already live

**Pull request closed without merging**
