### PR TITLE
add support for sha256 download hashes

### PR DESCRIPTION
**Pull request by vszakats**
After this patch the release process must also be updated to generate and upload `*.gz.sha256` hash files.

### CODE REVIEW

**Comment by vszakats** [comment]
Closing this due to no interest.

**Comment by richsalz** [comment]
well it took awhile but we did do it.

**Comment by vszakats** [comment]
I did notice it with the latest OpenSSL release, thanks a lot for confirming.

On the same roll, probably MD5 could be deleted, it doesn't convey 
a very good message and not very useful these days. (unless there are 
systems out there that don't have any support for something secure)

**Comment by richsalz** [comment]
i think the intent is only for older releases.

**Pull request closed without merging**
