### PR TITLE
Merge information from openssl.com and about OSS into main site

### PR DESCRIPTION
**Pull request by iamamoose**
The main openssl.org site already contains details about OSF and mentions OSS in many places (support contacts, fips etc) but then we have some minimal info on openssl.com too.  It would be better if they were all merged -- this patch adds the missing details about OSS to the contact page, adds the bylaws, and adds the page about getting a verification FIPS CD to openssl.org.  If this is accepted and merged we can then replace openssl.com with redirects rather than maintaining a separate site.

This PR also removes the "telephone" contact option (but the number wasn't given anyway), and removes the ability to pay for a verify CD by US Cheque/check as we do not wish to accept them at this time.

### CODE REVIEW

**Comment by levitte** [comment]
Does that mean that you think openssl.com should be aliased with openssl.org? Same landing page?

**Comment by iamamoose** [comment]
> Does that mean that you think openssl.com should be aliased with openssl.org? Same landing page?

We probably should do rewrites so openssl.com/* goes to https://www.openssl.org/community/contacts.html

**Comment by levitte** [comment]
... Except for the verifycd page, I suppose.
(are we having a link to that one, BTW?)

**Comment by levitte** [comment]
Having the contact page as a landing page is a good idea. I didn't like it a year or so ago, but have had a change of mind.

**Comment by t-j-h** [comment]
Hopefully we can move the verifycd to a separate authorised source for handling going forward.

**Comment by t-j-h** [comment]
The oss-bylaws file you have is out of date - and that probably means the osf-bylaws file on the website is also out of date.

**Comment by levitte** [comment]
Sure. We will still want to redirect the current URL to whatever it will be going forward, surely?

**Review by t-j-h — APPROVED** [review]

**Pull request merged**
