### PR TITLE
Add GeneralName question

### PR DESCRIPTION
**Pull request by richsalz**
Addressing https://github.com/openssl/openssl/issues/6610

### CODE REVIEW

**Comment by richsalz** [comment]
ping.  bump.  nudge.  hey.  whatever....

**Comment by richsalz** [comment]
ping @openssl/omc

**Review by vdukhovni — APPROVED** [review]
The text looks fine.  Don't know whether this is actually a frequently asked question, but if you think it belongs in the FAQ, no objections.

**Comment by richsalz** [comment]
It's been asked at least twice, and I forget the details when I try to answer. :)  Thanks!

**Pull request closed without merging**
