### PR TITLE
Redirect /policies/codingstyle.html

### LINKED ISSUE #317: Add to old location of coding guideline a forward pointer/redirect
As discussed in https://github.com/openssl/openssl/pull/18015:

The URL of the coding guidelines recently changed
from ~https://www.openssl.org/policies/codingstyle.htm~
https://www.openssl.org/policies/codingstyle.html
to https://www.openssl.org/policies/technical/coding-style.html.

Many search engines and likely also various external web pages still point to the old location.
So some forward pointer, ideally an automatic  redirect or rewrite rule should be placed there.

### PR DESCRIPTION
**Pull request by levitte**
Fixes #317

### CODE REVIEW

**Review by DDvO — APPROVED** [review]
LGTM

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged

c75034267f9edb1580a330fae91f2ef9fafa07d9 Redirect /policies/codingstyle.html

**Comment by DDvO** [comment]
Hmm, accessing https://www.openssl.org/policies/codingstyle.htm still yields **Page Not Found**.

**Comment by levitte** [comment]
> Hmm, accessing https://www.openssl.org/policies/codingstyle.htm still yields **Page Not Found**.

.htm**l**

**Comment by levitte** [comment]
(you'll note that https://www.openssl.org/policies/technical/coding-style.htm doesn't work either, while https://www.openssl.org/policies/technical/coding-style.html does)

**Comment by mspncp** [comment]
> Hmm, accessing https://www.openssl.org/policies/codingstyle.htm still yields **Page Not Found**.

I'm not sure why you believe that it used to be reachable with .htm only. I searched the web and source repos and I only found links ending in .html, e.g:

 https://github.com/openssl/web/commit/71dcd08ab8e43fcc4bb332657b1ea19d774dad25#diff-7d7d96bfdf1cbe25cf6489833b850376129740b5675b748ddf2fd00cdcfe6d37R42

https://github.com/openssl/openssl/commit/5f8e6c50bd862d6bb0bbd16b4c0b3be841d9cf32#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L48-R61

**Comment by DDvO** [comment]
Oh, it turns out that I had a copy&paste mistake, 
missing the final letter `l` in https://www.openssl.org/policies/codingstyle.html.

Sorry for the confusion!

**Pull request closed without merging**
