### PR TITLE
Handle document sectioning correctly

### PR DESCRIPTION
**Pull request by levitte**
Gone are the apps/, crypto/ and ssl/ directories.  We move to a Unix
manpage structure for older releases as well as new ones.

With that, there's no more need for a separate bin/mk-newmanpages,
bin/mk-manpages can handle both the old and the new POD directory
structure.

For a document tree that previously had apps/, crypto/ and ssl/, we
provide a .htaccess that accepts the old URLs and maps them correctly
to man1/ or man3/.

### CODE REVIEW

**Comment by levitte** [comment]
This should resolve the long standing issue where links between the old layout manpages aren't right.

**Comment by levitte** [comment]
This PR is currently active on https://beta.openssl.org/, please check it out.

**Comment by mattcaswell** [comment]
Umm...

https://beta.openssl.org/docs/man1.1.0/man3/

Gives me:

"an error occurred while processing this directive"

**Comment by levitte** [comment]
[sigh] that's because `make` only builds the master manpages...  I've now run `make manpages`, that should make things better.  But it doesn't, it seems I messed up redirections.  Hang on.

**Comment by levitte** [comment]
It's looking up!  (incidently, I noticed that `mk-apropos` includes index.html in the apropos...  that's another PR coming up)

**Comment by mattcaswell** [comment]
From this page:

https://beta.openssl.org/docs/man1.1.1/man3/ECDSA_SIG_new.html

If I click on the 1.0.2 link on the right hand side I correctly get taken to the 1.0.2 docs. Clicking on the 1.1.1 version to try and get back where I started results in "Page not found"

**Comment by levitte** [comment]
I've rebased on top of the mk-apropos fixup (#109) and am running another `make relupd` on beta.  Please have another look in a moment.

**Comment by mattcaswell** [comment]
Seems to be a common problem when looking at the 1.0.2 man pages. Another example:

https://beta.openssl.org/docs/manmaster/man3/BF_encrypt.html

The documentation exists in all versions. Clicking on the 1.0.2 version works:

https://beta.openssl.org/docs/man1.0.2/man3/BF_encrypt.html

But then trying to get back to a later version fails. Clicking on the 1.1.1 link for example gives you:

https://beta.openssl.org/docs/man1.1.1/man3/blowfish.html

Note the URL does no appear to be as expected. I would have expected:

https://beta.openssl.org/docs/man1.1.1/man3/BF_encrypt.html

**Comment by levitte** [comment]
Okie, will have a look at that

**Comment by levitte** [comment]
Oi....  that was a big can of worms.  I hadn't looked at the cross reference stuff, and that's extra tricky because some new version manpages do not exist in older versions.  Pfeww....

**Comment by mattcaswell** [comment]
*Ideally* links to older versions wouldn't appear if that man page doesn't exist in an older version. I guess some man pages might be split up into 2 or more different man pages between versions as well - which makes it even more complicated.

**Comment by levitte** [comment]
I'm making a cross reference generator that goes by simple file comparison.  Anything beyond that is subject for another PR, if anyone is inclined.  However, since we generate files for every *name* in the POD files, I suspect it will be OK.  The only thing I can think of is if there's any page that moved from one man section to another...  they should be very few, and I'm willing to see that as negligible.

**Comment by levitte** [comment]
@mattcaswell, please have another look.  It took a bit of time, but I think I got cross referencing down.  In particular, every page will only cross reference to other releases where the same page actually exists.

**Comment by levitte** [comment]
For example, if you look at https://beta.openssl.org/docs/manmaster/man3/OSSL_STORE_LOADER.html, you will only see links that allow you to go back and forth between master and 1.1.1, which is correct since it was added in 1.1.1...

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

1763c4db685b43c58b33d2ace0435da1a067ba24 bin/mk-mancross: new manpage cross reference script
8e80d7699c38ef890cc62da9fd713bcfc49152db bin/mk-manpages: refactor to allow cross references between releases
98d1be0a1bcd7ae582753e54b523faf6b4bd1360 Handle document sectioning correctly

**Pull request closed without merging**
