### PR TITLE
Turn off Markdown interpretation of HTML blocks in markdown files

### LINKED ISSUE #394: web page version of "man openssl-req" has broken formatting
Text formatting breaks in the section describing the option `-subj`, and it remains broken on the rest of the webpage.

https://www.openssl.org/docs/manmaster/man1/openssl-req.html

Screenshot:

openssl-req_20231219_122246

### PR DESCRIPTION
**Pull request by levitte**
Fixes openssl/project#394

### CODE REVIEW

**Review by t-j-h — DISMISSED** [review]

**Comment by levitte** [comment]
This fix wasn't right...  apparently, fix-man-html is no longer used, but wasn't removed...

Fixup coming up

**Comment by levitte** [comment]
Now it seems to do things right.  Re-review needed

**Comment by t8m** [comment]
What about underscores or asterisks? Are they handled correctly if they're present in the generated HTML?

**Comment by levitte** [comment]
> What about underscores or asterisks? Are they handled correctly if they're present in the generated HTML?

Actually, I'm remaking this PR completely.  It turns out that pandoc has this interpretation as an extension, which can be turned off (i.e. markdown interpretation in contents of HTML blocks can be turned off).

**Comment by levitte** [comment]
I'm making this draft, to allow myself some time to test this

**Comment by levitte** [comment]
Yup, works in my test!

**Review by hlandau — APPROVED** [review]

**Comment by levitte** [comment]
Merged

bea4e6cfa23c5da529753388e9fe233d714b5faf Turn off Markdown interpretation of HTML blocks in markdown files

**Pull request closed without merging**
