### PR TITLE
Reformat FAQ files

### PR DESCRIPTION
**Pull request by levitte**
Make the correct Markdown, and then use pandoc to create the FAQ HTML.
We then use CSS and a bit of Javascript to make it an accordion style
FAQ.

### CODE REVIEW

**Comment by richsalz** [comment]
Perhaps a mini-TOC at the top that jumps to each section.

**Comment by levitte** [comment]
Why?

**Comment by richsalz** [comment]
Because as I looked at the page on the beta site, I found myself wanting such a thing.

**Comment by levitte** [comment]
Better?

**Comment by richsalz** [comment]
very nice!

**Comment by levitte** [comment]
So, uhm, go?   no go?

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
Merged.

8557dd2bb3cebee18ec35347250271322b09d5da Reformat FAQ files

**Pull request closed without merging**
