### PR TITLE
Add the future series 3.2

### PR DESCRIPTION
**Pull request by levitte**
With the beta release, we also have the branch to produce things from

### CODE REVIEW

**Comment by levitte** [comment]
To be merged tomorrow, as part of the release of 3.2.0 beta 1

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Not sure why this is drafty.

**Comment by levitte** [comment]
> Not sure why this is drafty.

It turns out to be an effective way to avoid premature merging...

**Review by hlandau — APPROVED** [review]

**Comment by levitte** [comment]
Merged

d4c9499c9f8350b4f3aef516876accb77fb1bc0e Add the future series 3.2

**Pull request closed without merging**
